### ISSUE TITLE
New tab

### ISSUE THREAD

**Issue by ghost** [altimetrik-onboarding-uy/gcastro#8]
As a registered user, i need a new tab in the application showing a list of the compensations of all employees of the org.

**Comment by ghost** [comment]
The table shows the following columns:
Employee's name
Employee's date of birth (formatted as: January 14, 1979)
Job Category
Compensation Type
Amount
Location
Office
Submitted
Status

**Comment by GabiCastro10** [comment]
This table allows to switch between these views (ideally filtering the corresponding items):
All compensations.
Salary.
Study.
Research.

It would be nice if the table has zebra rows.
